# Generated by Django 4.2.2 on 2023-07-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='agency',
        ),
    ]
