# Generated by Django 4.2.2 on 2023-07-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_remove_transaction_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='no_tickets',
        ),
    ]
