# Generated by Django 4.2.2 on 2023-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='departure_time',
            field=models.CharField(max_length=10),
        ),
    ]
