# Generated by Django 4.2.2 on 2023-07-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_transaction_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof',
            field=models.ImageField(null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
